# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='organization_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
