# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160817_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
