# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 03:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
