# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0004_game_current_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_frame',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
