# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTraunche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
