# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20160817_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketgroup',
            name='price',
        ),
    ]
