# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160817_1929'),
        ('tickets', '0005_ticket_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgroup',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
