# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketgroup_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticketgroup'),
        ),
    ]
