# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20160817_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='claimed_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_svg',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
