# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20160818_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
